//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Deserialize, Serialize)]
#[sea_orm(table_name = "event")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: u32,
  pub website_id: u32,
  pub visitor_id: String,
  pub r#type: String,
  pub tag: String,
  pub url_path: String,
  pub url_query: String,
  pub page_title: String,
  pub created_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
